# Introduction

Welcome to the Cloud-SPAN Community Handbook! It's great to see you here.

## About Cloud-SPAN
Cloud-SPAN deploys high quality learning resources that will train researchers to effectively generate and analyse a range of 'omics data using Cloud computing resources.

Cloud-SPAN is a collaboration between the [Department of Biology](https://www.york.ac.uk/biology/) at the University of York and the [Software Sustainability Institute](https://www.software.ac.uk/), and funded by the [UKRI innovation scholars award](https://www.ukri.org/news/initiatives-boost-health-and-bioscience-skills-and-industry/) under project reference [MR/V038680/1](https://gtr.ukri.org/projects?ref=MR%2FV038680%2F1).

## About this handbook
This handbook is intended as a reference for both the core Cloud-SPAN team (see below) and for our wider community of learners. It's where you'll find our [Code of Conduct], contributing guidelines and other practical information which will help you make the most of our resources in a friendly, understanding environment. 

For example, did you know that we have an online forum for questions, suggestions and any concerns you might have about applying what you learn on our courses? We strongly encourage you to engage with the Cloud-SPAN community to enhance your learning and understanding. You can find the forum [here](cloudspan.peerboard.com) or read more about [using Peerboard](#forum) later in this manual.

## Our Team
### Project team

| Name | Role | % working on the project | Time period allocated to the project | Institution |
|---|---|---|---|---|
| Emma Rand | Project oversight | 20% | 2020-22  | Uni of York |
| James Chong | Project oversight |  10% | 2020-22|  Uni of York |
| Jorge Buenabad-Chavez | Content developer and Cloud deliverer | 100% | 2020-22 | Uni of York |
| Evelyn Greeves | Content developer and FAIR/CoP deliverer | 60% | 2020-22 | Uni of York |
| Sarah Dowsland | Administrator | 50% | 2020-22 | Uni of York |
| Annabel Cansdale | Content developer | 20% | 2020-22 | Uni of York |
| Sarah Forrester | Content developer | 20% | 2020-22 | Uni of York |
| Neil Chue Hong | Straetgic advisor  | 10% | 2020-22 | Software Sustainability Institute |
