# FAIR Principles

## What is FAIR data?
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">
FAIR data is **Findable**, **Accessible**, **Interoperable** and **Reusable**.
</div>
These principles are designed to help both humans and machines find and reuse data as easily as possible. They are aspirational but tangible steps can be made towards realising them.

### Findable {-}
**Findable** is all about making sure data/resources are as easy to find as possible.

How we're making resources **findable** at Cloud-SPAN:

- We will be assigning persistent identifiers to our teaching materials to prevent "link rot", or broken links.
- We will register our teaching materials with an appropriate registry (e.g. Carpentries Incubator), so it is easier to find.
- We will be describing all our resources with rich metadata so it can be aggregated by the right registries.

### Accessible {-}
**Accessible** means it is easy to find out how to access the data/resources.

How we're making resources **accessible** at Cloud-SPAN:

- xyz

### Interoperable {-}
**Interoperable** means data/resources can be easily integrated with other data/resources, and be viewable in different programs, applications or workflows.

How we're making resources **interoperable** at CLOUD-SPAN:

- xyz

### Reusable {-}
**Reusable** is about making sure that data/resources are suitable for re-use in different settings.

How we're making resources **reusable** at CLOUD-SPAN:

- xyz
