project:
  type: book

book:
  title: "Cloud-SPAN Handbook"
  author: "Evelyn Greeves"
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - code-of-conduct.qmd
    - our-courses.qmd
    - contributing-guide.qmd
    - FAIR-principles.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: images/cloud-span-logo-square.png