---
number-depth: 1
---

# The Cloud-SPAN commmunity {#community}

Our aim is to build a friendly and involved community of people who have used our resources, are interested in our resources, or who have expertise in the areas we cover.

That means that whether you are...\

🧬 an expert in 'omics analyses\
🤔 a complete newbie at 'omics\
🤷 not entirely sure what an "omic" is\
☁️ an experienced Cloud user\
😵 a little bewildered by the Cloud\

...then the Cloud-SPAN community is for you!

There are lots of ways to contribute and we welcome all of them! Contributing, and joining our community, doesn't have to mean writing technical code.

Here are some ideas of ways you can contribute:

## Ways to contribute {#ways-to-contribute}

### Learn

- Attend or work through one of our [courses](#courses).

### Connect

- Join our *Community of Practice*.
- Come along to one of our code retreats to get help applying your skills and meet other researchers working in similar fields.

### Help

- Tell us about bugs or problems you encounter in the course.

### Expand

- Suggest new/different software tools for analysis.
- Contribute new examples.
- Attend one of our 'Train the Trainer" courses so you can take parts of the course back to teach at your home institution.

## Using GitHub to contribute

We use GitHub as a tool for managing version control (AKA keeping a record of the project's development). This helps us stay accountable and transparent. It's also one of the ways we are making steps towards adhering to the [FAIR Principles\](#fair-principles).

If you want to contribute any content such as an update to the course or a new example then via GitHub is the best place to get in contact. For lots more guidance about how to contribute via GitHub, read our [GitHub Contribution Guide](https://github.com/Cloud-SPAN/CloudSPAN-handbook/blob/main/CONTRIBUTING.md).

Git (the programming language underlying Github) and Github can be a little intimidating at first but don't worry, the team are here to hold your hand! 🤝
